name: vetitiliber
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ##dependencia para los toast
  fluttertoast: ^8.0.7
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  sqflite: ^1.3.0
  intl: ^0.17.0
  shared_preferences: ^2.0.6

  file_picker: ^3.0.3
  
  flutter_pdfview: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter




flutter:
  
  uses-material-design: true
  assets:
   - assets/imagenes/login/pe.jpg
   - assets/imagenes/login/LOGO2.png
   