-- MySQL Script generated by MySQL Workbench
-- Wed Jul  7 16:54:17 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- USE `myReview` ;

-- -----------------------------------------------------
-- Table `usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuario` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `contrasena` VARCHAR(45) NOT NULL,
  `fotoPerfil` VARCHAR(150) NULL,
  `correoElectronico` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coleccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coleccion` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `genero` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autor` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libro` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `sinopsis` VARCHAR(1500) NOT NULL,
  `genero_id` INT UNSIGNED NOT NULL,
  `autor_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_libro_genero1_idx` (`genero_id` ASC),
  INDEX `fk_libro_autor1_idx` (`autor_id` ASC),
  CONSTRAINT `fk_libro_genero1`
    FOREIGN KEY (`genero_id`)
    REFERENCES `genero` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_libro_autor1`
    FOREIGN KEY (`autor_id`)
    REFERENCES `autor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `saga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saga` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `resena`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resena` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `calificacion` INT UNSIGNED NOT NULL,
  `contenido` VARCHAR(45) NOT NULL,
  `usuario_id` INT UNSIGNED NOT NULL,
  `libro_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_resena_usuario1_idx` (`usuario_id` ASC),
  INDEX `fk_resena_libro1_idx` (`libro_id` ASC),
  CONSTRAINT `fk_resena_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resena_libro1`
    FOREIGN KEY (`libro_id`)
    REFERENCES `libro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuario_has_coleccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuario_has_coleccion` (
  `usuario_id` INT UNSIGNED NOT NULL,
  `coleccion_id` INT UNSIGNED NOT NULL,
  `libro_id` INT UNSIGNED NOT NULL,
  INDEX `fk_usuario_has_coleccion_coleccion1_idx` (`coleccion_id` ASC),
  INDEX `fk_usuario_has_coleccion_usuario1_idx` (`usuario_id` ASC),
  INDEX `fk_usuario_has_coleccion_libro1_idx` (`libro_id` ASC),
  CONSTRAINT `fk_usuario_has_coleccion_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_coleccion_coleccion1`
    FOREIGN KEY (`coleccion_id`)
    REFERENCES `coleccion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_coleccion_libro1`
    FOREIGN KEY (`libro_id`)
    REFERENCES `libro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reaccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reaccion` (
  `resena_id` INT UNSIGNED NOT NULL,
  `usuario_id` INT UNSIGNED NOT NULL,
  `like` INT UNSIGNED NOT NULL,
  `dislike` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`resena_id`, `usuario_id`),
  INDEX `fk_resena_has_usuario_usuario1_idx` (`usuario_id` ASC),
  INDEX `fk_resena_has_usuario_resena1_idx` (`resena_id` ASC),
  CONSTRAINT `fk_resena_has_usuario_resena1`
    FOREIGN KEY (`resena_id`)
    REFERENCES `resena` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resena_has_usuario_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `A_sigue_B`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `A_sigue_B` (
  `usuarioA_id` INT UNSIGNED NOT NULL,
  `usuarioB_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`usuarioA_id`, `usuarioB_id`),
  INDEX `fk_usuario_has_usuario_usuario2_idx` (`usuarioB_id` ASC),
  INDEX `fk_usuario_has_usuario_usuario1_idx` (`usuarioA_id` ASC),
  CONSTRAINT `fk_usuario_has_usuario_usuario1`
    FOREIGN KEY (`usuarioA_id`)
    REFERENCES `usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_usuario_usuario2`
    FOREIGN KEY (`usuarioB_id`)
    REFERENCES `usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `configuracion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `configuracion` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nComentarios` INT UNSIGNED NOT NULL,
  `nReacciones` INT UNSIGNED NOT NULL,
  `vLibros` INT UNSIGNED NOT NULL,
  `vResenas` INT UNSIGNED NOT NULL,
  `vPerfil` INT UNSIGNED NOT NULL,
  `usuario_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_configuracion_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_configuracion_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `invisible`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `invisible` (
  `configuracion_id` INT UNSIGNED NOT NULL,
  `libro_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`configuracion_id`, `libro_id`),
  INDEX `fk_configuracion_has_libro_libro1_idx` (`libro_id` ASC),
  INDEX `fk_configuracion_has_libro_configuracion1_idx` (`configuracion_id` ASC),
  CONSTRAINT `fk_configuracion_has_libro_configuracion1`
    FOREIGN KEY (`configuracion_id`)
    REFERENCES `configuracion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_configuracion_has_libro_libro1`
    FOREIGN KEY (`libro_id`)
    REFERENCES `libro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `saga_has_libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saga_has_libro` (
  `saga_id` INT UNSIGNED NOT NULL,
  `libro_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`saga_id`, `libro_id`),
  INDEX `fk_saga_has_libro_libro1_idx` (`libro_id` ASC),
  INDEX `fk_saga_has_libro_saga1_idx` (`saga_id` ASC),
  CONSTRAINT `fk_saga_has_libro_saga1`
    FOREIGN KEY (`saga_id`)
    REFERENCES `saga` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_saga_has_libro_libro1`
    FOREIGN KEY (`libro_id`)
    REFERENCES `libro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comentario` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `contenido` VARCHAR(45) NOT NULL,
  `resena_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comentario_resena1_idx` (`resena_id` ASC),
  CONSTRAINT `fk_comentario_resena1`
    FOREIGN KEY (`resena_id`)
    REFERENCES `resena` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `A_responde_B`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `A_responde_B` (
  `comentarioA_id` INT UNSIGNED NOT NULL,
  `comentarioB_id` INT UNSIGNED NOT NULL,
  INDEX `fk_comentario_has_comentario_comentario2_idx` (`comentarioB_id` ASC),
  INDEX `fk_comentario_has_comentario_comentario1_idx` (`comentarioA_id` ASC),
  CONSTRAINT `fk_comentario_has_comentario_comentario1`
    FOREIGN KEY (`comentarioA_id`)
    REFERENCES `comentario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentario_has_comentario_comentario2`
    FOREIGN KEY (`comentarioB_id`)
    REFERENCES `comentario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;