-- MySQL Script generated by MySQL Workbench
-- Mon Jul 12 12:58:42 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- DATABASE myReview
-- -----------------------------------------------------

-- -----------------------------------------------------
-- DATABASE myReview
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `myReview` DEFAULT CHARACTER SET utf8 ;
USE `myReview` ;

-- -----------------------------------------------------
-- Table `myReview`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myReview`.`usuario` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `contrasena` VARCHAR(45) NOT NULL,
  `fotoPerfil` VARCHAR(150) NULL,
  `correoElectronico` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myReview`.`coleccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myReview`.`coleccion` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myReview`.`autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myReview`.`autor` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myReview`.`libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myReview`.`libro` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `sinopsis` VARCHAR(1500) NOT NULL,
  `portada` VARCHAR(350) NOT NULL,
  `autor_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_libro_autor1_idx` (`autor_id` ASC),
  CONSTRAINT `fk_libro_autor1`
    FOREIGN KEY (`autor_id`)
    REFERENCES `myReview`.`autor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myReview`.`genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myReview`.`genero` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myReview`.`saga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myReview`.`saga` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myReview`.`resena`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myReview`.`resena` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `calificacion` INT UNSIGNED NOT NULL,
  `contenido` VARCHAR(200) NOT NULL,
  `usuario_id` INT UNSIGNED NOT NULL,
  `libro_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_resena_usuario1_idx` (`usuario_id` ASC),
  INDEX `fk_resena_libro1_idx` (`libro_id` ASC),
  CONSTRAINT `fk_resena_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `myReview`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resena_libro1`
    FOREIGN KEY (`libro_id`)
    REFERENCES `myReview`.`libro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myReview`.`usuario_has_coleccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myReview`.`usuario_has_coleccion` (
  `usuario_id` INT UNSIGNED NOT NULL,
  `coleccion_id` INT UNSIGNED NOT NULL,
  `libro_id` INT UNSIGNED NOT NULL,
  INDEX `fk_usuario_has_coleccion_coleccion1_idx` (`coleccion_id` ASC),
  INDEX `fk_usuario_has_coleccion_usuario1_idx` (`usuario_id` ASC),
  INDEX `fk_usuario_has_coleccion_libro1_idx` (`libro_id` ASC),
  CONSTRAINT `fk_usuario_has_coleccion_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `myReview`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_coleccion_coleccion1`
    FOREIGN KEY (`coleccion_id`)
    REFERENCES `myReview`.`coleccion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_coleccion_libro1`
    FOREIGN KEY (`libro_id`)
    REFERENCES `myReview`.`libro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myReview`.`reaccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myReview`.`reaccion` (
  `resena_id` INT UNSIGNED NOT NULL,
  `usuario_id` INT UNSIGNED NOT NULL,
  `like` INT UNSIGNED NOT NULL,
  `dislike` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`resena_id`, `usuario_id`),
  INDEX `fk_resena_has_usuario_usuario1_idx` (`usuario_id` ASC),
  INDEX `fk_resena_has_usuario_resena1_idx` (`resena_id` ASC),
  CONSTRAINT `fk_resena_has_usuario_resena1`
    FOREIGN KEY (`resena_id`)
    REFERENCES `myReview`.`resena` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resena_has_usuario_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `myReview`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myReview`.`A_sigue_B`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myReview`.`A_sigue_B` (
  `usuarioA_id` INT UNSIGNED NOT NULL,
  `usuarioB_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`usuarioA_id`, `usuarioB_id`),
  INDEX `fk_usuario_has_usuario_usuario2_idx` (`usuarioB_id` ASC),
  INDEX `fk_usuario_has_usuario_usuario1_idx` (`usuarioA_id` ASC),
  CONSTRAINT `fk_usuario_has_usuario_usuario1`
    FOREIGN KEY (`usuarioA_id`)
    REFERENCES `myReview`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_usuario_usuario2`
    FOREIGN KEY (`usuarioB_id`)
    REFERENCES `myReview`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myReview`.`configuracion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myReview`.`configuracion` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nComentarios` INT UNSIGNED NOT NULL,
  `nReacciones` INT UNSIGNED NOT NULL,
  `vLibros` INT UNSIGNED NOT NULL,
  `vResenas` INT UNSIGNED NOT NULL,
  `vPerfil` INT UNSIGNED NOT NULL,
  `usuario_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_configuracion_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_configuracion_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `myReview`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myReview`.`invisible`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myReview`.`invisible` (
  `configuracion_id` INT UNSIGNED NOT NULL,
  `libro_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`configuracion_id`, `libro_id`),
  INDEX `fk_configuracion_has_libro_libro1_idx` (`libro_id` ASC),
  INDEX `fk_configuracion_has_libro_configuracion1_idx` (`configuracion_id` ASC),
  CONSTRAINT `fk_configuracion_has_libro_configuracion1`
    FOREIGN KEY (`configuracion_id`)
    REFERENCES `myReview`.`configuracion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_configuracion_has_libro_libro1`
    FOREIGN KEY (`libro_id`)
    REFERENCES `myReview`.`libro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myReview`.`saga_has_libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myReview`.`saga_has_libro` (
  `saga_id` INT UNSIGNED NOT NULL,
  `libro_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`saga_id`, `libro_id`),
  INDEX `fk_saga_has_libro_libro1_idx` (`libro_id` ASC),
  INDEX `fk_saga_has_libro_saga1_idx` (`saga_id` ASC),
  CONSTRAINT `fk_saga_has_libro_saga1`
    FOREIGN KEY (`saga_id`)
    REFERENCES `myReview`.`saga` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_saga_has_libro_libro1`
    FOREIGN KEY (`libro_id`)
    REFERENCES `myReview`.`libro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myReview`.`comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myReview`.`comentario` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `contenido` VARCHAR(45) NOT NULL,
  `resena_id` INT UNSIGNED NOT NULL,
  `usuario_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comentario_resena1_idx` (`resena_id` ASC),
  INDEX `fk_comentario_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_comentario_resena1`
    FOREIGN KEY (`resena_id`)
    REFERENCES `myReview`.`resena` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentario_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `myReview`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myReview`.`A_responde_B`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myReview`.`A_responde_B` (
  `comentarioA_id` INT UNSIGNED NOT NULL,
  `comentarioB_id` INT UNSIGNED NOT NULL,
  INDEX `fk_comentario_has_comentario_comentario2_idx` (`comentarioB_id` ASC),
  INDEX `fk_comentario_has_comentario_comentario1_idx` (`comentarioA_id` ASC),
  CONSTRAINT `fk_comentario_has_comentario_comentario1`
    FOREIGN KEY (`comentarioA_id`)
    REFERENCES `myReview`.`comentario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentario_has_comentario_comentario2`
    FOREIGN KEY (`comentarioB_id`)
    REFERENCES `myReview`.`comentario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myReview`.`libro_has_genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myReview`.`libro_has_genero` (
  `libro_id` INT UNSIGNED NOT NULL,
  `genero_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`libro_id`, `genero_id`),
  INDEX `fk_libro_has_genero_genero1_idx` (`genero_id` ASC),
  INDEX `fk_libro_has_genero_libro1_idx` (`libro_id` ASC),
  CONSTRAINT `fk_libro_has_genero_libro1`
    FOREIGN KEY (`libro_id`)
    REFERENCES `myReview`.`libro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_libro_has_genero_genero1`
    FOREIGN KEY (`genero_id`)
    REFERENCES `myReview`.`genero` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
